language: csharp
mono: none
dotnet: 3.1
solution: MovieRatingCompolsutory.sln
install:
- dotnet restore
script:
- dotnet build
- dotnet test MovieRatingTest/MovieRatingTest.csproj
notifications:
  email: false
  slack:
    rooms:
      - secure: 3qaNoloGhHjmb5kc5qlueOcZeR0Ns2LLaSS2RficYuQecnWQffaTyp6hwnbWfu82KMTS4Zn8GRD4CbEDkGRvyhH7eHDOEytlEUik8t0ECNUw3PofLUPzb8E/jJlfWQAPdI6SPbGl2OMIyYZI28esoS73NPyEP/pu8oXFZe9JPgAVURNwP6LSciy2Z7ro5OOtC0jxvgCXdZ5liRC3XFkX81+CHtz1RT6mB56vycBVD4MOvI3PrayOPgaUT2p2YqWf/ICJOaN/NNcn0XroYl/64Hz2NHMXNoULw1q2vohYe0Pyg2gZZa7hnKES0F6NTXLHn4Eekho83dDRM+xfMXst1vFp2taKtt42m62keFmzQ9JkhxwhUCwlwHKXBktH0hbw2gzBlrUfzM0h9Am7XMFNGE9QXdWxy2lsFQ3p+LSKC90hHhWmN+l3SgEaanj0GUA/T0kbrWHnO7Z5NaU8orB3Y2WJycQcvEJeM3nz4ZrpgJZgNLODGHRC9AJnJAMLWDW1xuxTkbdXBCyFwupSiATlzER/v8cS/herCJkcJVspjs1qPw/9ra8MseKdvFZA6nF12xJSc1AWW6aCJpJ8IDUcDDI2Dkmf9CjvX+BAkSo/0ytqGhnLbr0Zb0OWqWQkAOIwDbUg/z8uDkv02Poj7JX9S0xTeAFIxrZencjW8zh/ZOI=
    on_success: always
    on_failure: always